"""empty message

Revision ID: d36e1ebf002f
Revises: 
Create Date: 2024-04-20 17:12:03.401560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36e1ebf002f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_address', sa.String(length=500), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=50), nullable=True),
    sa.Column('address_line', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
